export const payload_all = {
  __args: [
    null,
    2024,
    { vt_filter: { datefrom: "2025-02-24", dateto: "2025-03-02" } },
    {
      op: "fetch",
      needed_part: {
        teachers: [
          "short",
          "name",
          "firstname",
          "lastname",
          "callname",
          "subname",
          "code",
          "cb_hidden",
          "expired",
        ],
        classes: [
          "short",
          "name",
          "firstname",
          "lastname",
          "callname",
          "subname",
          "code",
          "classroomid",
        ],
        classrooms: [
          "short",
          "name",
          "firstname",
          "lastname",
          "callname",
          "subname",
          "code",
        ],
        igroups: [
          "short",
          "name",
          "firstname",
          "lastname",
          "callname",
          "subname",
          "code",
        ],
        students: [
          "short",
          "name",
          "firstname",
          "lastname",
          "callname",
          "subname",
          "code",
          "classid",
        ],
        subjects: [
          "short",
          "name",
          "firstname",
          "lastname",
          "callname",
          "subname",
          "code",
        ],
        events: ["typ", "name"],
        event_types: ["name", "icon"],
        subst_absents: ["date", "absent_typeid", "groupname"],
        periods: [
          "short",
          "name",
          "firstname",
          "lastname",
          "callname",
          "subname",
          "code",
          "period",
          "starttime",
          "endtime",
        ],
        dayparts: ["starttime", "endtime"],
        dates: ["tt_num", "tt_day"],
      },
      needed_combos: {},
    },
  ],
  __gsh: "00000000",
};

export const payload_current = {
  __args: [
    null,
    {
      year: 2024,
      datefrom: "2025-02-24",
      dateto: "2025-02-24",
      table: "classes",
      id: "-910",
      showColors: true,
      showIgroupsInClasses: false,
      showOrig: true,
      log_module: "CurrentTTView",
      subjects: true,
    },
  ],
  __gsh: "00000000",
};
